name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Publish to PyPi Using Poetry
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install latest version of Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python -
        - name: Add Poetry to $PATH
          run: |
            echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
        - name: Install deps
          run: |
            poetry install 
        - run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
        - name: Publish package
          run: poetry publish --build
            

    